apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: managedresourcegroups.platform.essity
spec:
  group: platform.essity
  names:
    categories:
      - crossplane
      - azure
    listKind: azureResourceList
    shortNames:
      - mresourcegroup
      - mrg
    kind: ManagedResourceGroup
    plural: managedresourcegroups
  claimNames:
    kind: ManagedResourceGroupClaim
    plural: managedresourcegroupclaims
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=='Established')].status
          name: ESTABLISHED
          type: string
        - jsonPath: .status.conditions[?(@.type=='Offered')].status
          name: OFFERED
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metadata:
                  type: object
                  properties:
                    name:
                      type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                spec:
                  type: object
                  required:
                    - region
                    - name
                    - solutionId
                    - costCenter
                    - environment
                    - owner
                  properties:
                    region:
                      type: string
                      enum:
                        - westeurope
                        - southeastasia
                        - northeurope
                      default: westeurope
                    name:
                      type: string
                    solutionId:
                      type: integer
                    costCenter:
                      type: string
                    environment:
                      type: string
                      enum:
                        - dev
                        - test
                        - prod
                      default: dev
                    owner:
                      type: string
                    subscriptionId:
                      type: string
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                      default:
                        provisioner: crossplane
                        created-by: crossplane
