apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xazuresqls.crossplane.essity.dev
spec:
  group: crossplane.essity.dev
  names:
    categories:
      - crossplane
      - azure
    listKind: azureResourceList
    shortNames:
      - xazuresql
      - azuresql
    kind: XAzureSQL
    plural: xazuresqls
  claimNames:
    kind: AzureSQL
    plural: azuresqls
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=='Established')].status
          name: ESTABLISHED
          type: string
        - jsonPath: .status.conditions[?(@.type=='Offered')].status
          name: OFFERED
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - region
                    - resourceGroup
                    - serverName
                    - databases
                  properties:
                    region:
                      type: string
                      enum: 
                        - westeurope
                        - southeastasia
                        - northeurope
                      default: westeurope
                    resourceGroup:
                      type: string
                    serverName:
                      type: string
                    databases:
                      type: array
                      items:
                        type: object
                        required:
                          - name
                          - skuTier
                        properties:
                          name:
                            type: string
                            minLength: 4
                          collation:
                            type: string
                          maxSizeGB:
                            type: integer
                            minimum: 5
                          skuName:
                            type: string
                            default: S0
                          skuTier:
                            type: string
