apiVersion: resources.azapi.upbound.io/v1beta1
kind: Resource
metadata:
  name: azapiresourcegroup
spec:
  providerConfigRef:
    name: azapi
  forProvider:
    type: "Microsoft.Resources/resourceGroups@2024-07-01"
    parentId: "/subscriptions/f2024049-e6cb-4489-9270-6d0d6cd65018/"
    location: "westeurope"
    name: "rg-crossplane-with-vimal"
    schemaValidationEnabled: false
    ignoreBodyChanges:
      - "properties.accessTier"
      - "properties.kind"
    ignoreMissingProperty: false
    removingSpecialChars: false
    identity:
    #   - type: SystemAssigned
    tags:
      app: "example-app"
      business-context: "example-business"
      solution-id: "1234"
      created-by: "crossplane"
      cost-center: "poc"
      technical-owner: "vimal.vijayan@essity.com"
      owner: "vimal.vijayan@essity.com"
      criticality: "low"
      created-date: "2023-10-01"
      data-classification: "public"
      environment: "dev"
    body: |-
      {
        "properties": {}
      }
